package ch.ffhs.ftoop.interceptor.dame;

import ch.ffhs.ftoop.interceptor.dame.beans.*;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.util.Locale;
import java.util.Optional;
import java.util.ResourceBundle;

/**
 * 
 * Main GUI-Class. Controls the scenes.
 * 
 * @author MajorTwip
 * @version 0.8
 */
public class GUI implements DameGUIInterface {

    private Backend backend;
    private Stage stage;
    private ResourceBundle texts;
    GUIBoard guiboard=null;

    /**
     * GUI. Sets title
     * 
     * @param stage Primary stage generated by launch() in the Main-Class
     */
    GUI(Stage stage) {
        this.stage = stage;
        texts = ResourceBundle.getBundle("gui_texts", new Locale("EN"));


        stage.setTitle(texts.getString("title"));
        //stage.setMaximized(true);
        //stage.setMinWidth(640);
        //stage.setMinHeight(640);
    }

    /**
     * Creates Menubar
     * @return MenuBar to add to scene
     */
    private MenuBar getMenu() {
        MenuBar menubar = new MenuBar();

        Menu menuGame = new Menu("Game");

        MenuItem menuItemNewGame = new MenuItem("New Game");
        menuItemNewGame.setOnAction(e -> backend.startNewGame(GameMode.SinglePlayer8X8));

        MenuItem menuItemQuit = new MenuItem("Quit");
        menuItemQuit.setOnAction(e -> backend.quitGame());

        menuGame.getItems().addAll(menuItemNewGame, menuItemQuit);

        menubar.getMenus().addAll(menuGame);

        return menubar;
    }

    /**
     * Set Backend of the game
     * @param backend Backend class which shares 
     */
    void setBackend(Backend backend) {
        this.backend = backend;
    }

    /**
     * shows Menu as defined in Class GUIMenu
     */
    @Override
    public void showMenu() {
        stage.setScene(new Scene(new GUIMenu(backend)));
        stage.show();
    }
    
    
    /**
     * shows Game as defined in Class GUIBoard
     */
    @Override
    public void showBoard(Board board) {
        Scene scene = new Scene(new VBox());
        ((VBox) scene.getRoot()).getChildren().add(getMenu());

        guiboard = new GUIBoard(board, backend);
        ((VBox) scene.getRoot()).getChildren().add(guiboard);

        stage.setScene(scene);
        stage.show();
        guiboard.draw();
    }

    /**
     * Request termination to backend
     */
    @Override
    public void closeApplication() {
        backend.quitGame();
    }

    /**
     * Indicates players turn
     */
    @Override
    public void initiateTurn() {

    }

    
    
    @Override
    /**
     * shows a messageBox as defined in class MessageBox
     * @param msgbox Instance of class MessageBox which will be showed
     */
    public boolean showMessageBox(MessageBox msgbox) {
        Alert alert;
        switch (msgbox.getType()) {
            case OK:
                alert = new Alert(AlertType.INFORMATION);
                alert.setTitle(msgbox.getTitle());
                alert.setContentText(msgbox.getMessage());
                if (!msgbox.getHeader().equals("")) alert.setHeaderText(msgbox.getHeader());
                break;
            case LOSE:
                alert = new Alert(AlertType.INFORMATION);
                alert.setTitle(texts.getString("msg_lost_title"));
                alert.setContentText(texts.getString("msg_lost_content"));
                break;
            case VICTORY:
                alert = new Alert(AlertType.INFORMATION);
                alert.setTitle(texts.getString("msg_win_title"));
                alert.setContentText(texts.getString("msg_win_content"));
                break;
            case YESNO:
                alert = new Alert(AlertType.CONFIRMATION);
                alert.setTitle(msgbox.getTitle());
                alert.setContentText(msgbox.getMessage());
                if (!msgbox.getHeader().equals("")) alert.setHeaderText(msgbox.getHeader());
                break;
            default:
                alert = new Alert(AlertType.INFORMATION);
                break;
        }

        Optional<ButtonType> response = alert.showAndWait();
        return response.isPresent() && response.get() == ButtonType.OK;
    }

    @Override
    /**
     * animate a disappearing/reappearing stone.
     * bypass to GUIBoard
     * @param stone Stone to move
     * @param coordinate Coordinate to move stone to
     */
    public void animateMove(Stone stone, Coordinate coordinate) {
        if(guiboard!=null) {
        	guiboard.animateMove(stone, coordinate);
        }
    }

    @Override
    /**
     * animate a disappearing stone.
     * bypass to GUIBoard
     * @param stone Stone to remove
     */
    public void animateStoneRemove(Stone stone) {
    	 if(guiboard!=null) {
         	guiboard.animateStoneRemove(stone);
         }
    }
    
    /**
     * refresh board
     * bypass to GUIBoard
     */
    void redraw() {
    	guiboard.redraw();
    }

}
